config/routes.rb
Auctionx::Application.routes.draw do
  resources :bidders

  resources :bids

  devise_for :users

  resources :auctions
  
  root :to => 'auctions#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  
  SCHEDULED = 0
  ACTIVE = 1
  CANCELLED = 2
  COMPLETED = 3
  
  LIMIT = 5
  
  scope :scheduled, lambda{ where(status: SCHEDULED).limit(LIMIT)}
  scope :active, lambda{ where(status: ACTIVE).limit(LIMIT)}  
  scope :cancelled, lambda{ where(status: CANCELLED).limit(LIMIT)}
  scope :completed, lambda{ where(status: COMPLETED).limit(LIMIT)}
  
  before_create :parse_auction_id, :set_description
  after_create :spawn_auction_process
  after_destroy :kill_watcher_process
  
  def current_price
    bids.last.nil? ? "N/A" : bids.last.price
  end
  
  def total_bids
    bids.count
  end

  def last_active_bidders
    bids.select("distinct(bidder_id), bidders.username, count(*) as total_bids, MAX(bid_time) as latest_bid").
         group("bidder_id").
         joins(:bidder).
         order("MAX(bid_time) desc").limit(LIMIT)
  end

  def most_active_bidders
    bids.select("DISTINCT(bidder_id), bidders.username, count(*) as total_bids, MAX(bid_time) as latest_bid").
         order("total_bids desc").
         group("bidder_id").
         joins(:bidder).limit(LIMIT)
  end
  
private
  def kill_watcher_process
    system "kill -9 #{process_id}"
  end

  def parse_auction_id
    self.site_id = url.scan(/auction_id=(\d*)/).flatten.first
  end
  
  def set_description
    agent = Mechanize.new { |agent| agent.user_agent_alias = 'Mac Safari'} 
    page = agent.get(url)
    self.description = page.title
  end
  
  def spawn_auction_process
    pid = Process.spawn("rails runner \"DealDash.run('#{id}')\" -e #{Rails.env}")
    Process.detach pid
    self.process_id = pid
    self.save
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    if params[:filter]
      @results = Auction.send params[:filter].to_sym
      render :action => "filtered"
    else
      @scheduled = Auction.scheduled
      @active = Auction.active
      @completed = Auction.completed  
    end
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @auction = Auction.find(params[:id])
    @most_active_bidders = @auction.most_active_bidders
    @last_active_bidders = @auction.last_active_bidders

    respond_to do |format|
      format.html # show.html.erb
      format.js      
      format.json { render json: @auction }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.json
  def new
    @auction = Auction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(params[:auction])
    @auction.user = current_user

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render json: @auction, status: :created, location: @auction }
      else
        format.html { render action: "new" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.json
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
  def status(status)
    case status
      when Auction::SCHEDULED then "Scheduled"
      when Auction::ACTIVE then "Active"
      when Auction::COMPLETED then "Completed"      
    end
  end
end

app/views/auctions/_auction.html.erb
<tr>
  <td><%= link_to auction.description, auction %></td>    
  <td><%= auction.url %></td>
  <td><%= number_with_delimiter auction.total_bids %></td>
  <td><%= number_to_currency auction.current_price %></td>  
  <td><%= link_to 'Delete', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label>Auction URL</label>
    <div class="controls">
      <%= f.text_field :url %>
    </div>
  </div>
  
  <div class="control-group">
    <div class="controls">
      <%= f.submit :class => "btn btn-primary " %>
    </div>
  </div>  
<% end %>

app/views/auctions/_last_active_bidders.html.erb
<tr>
  <td><%= last_active_bidders.username %></td>
  <td><%= last_active_bidders.total_bids %></td>
  <td><%= format_time(last_active_bidders.latest_bid) %></td>
</tr>

app/views/auctions/_most_active_bidders.html.erb
<tr>
  <td><%= most_active_bidders.username %></td>
  <td><%= most_active_bidders.total_bids %></td>
  <td><%= format_time(most_active_bidders.latest_bid) %></td>
</tr>

app/views/auctions/_summary.html.erb
<b>Current Price:</b> <%= number_to_currency auction.current_price %><br>
<b>Total Bids:</b> <%= number_with_delimiter auction.total_bids %><br>
<b>Status:</b> <span id="auction_status"><%= status(auction.status) %></span><br>
<%= link_to "View Auction", auction.url %><br>

app/views/auctions/edit.html.erb
<h1>Edit Auction</h1>

<%= render 'form' %>
<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<h1>Auctions</h1><br>

<h4>Scheduled</h4>
<% if @scheduled.blank? %>
  <p>No Scheduled Auctions</p><br>
<% else %>
  <table class="table table-bordered table-striped table-condensed">
    <thead><tr>
      <th>Description</th>    
      <th>URL</th>
      <th>Total Bids</th>
      <th>Price</th>
      <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @scheduled %>
    </tbody>
  </table>
  <p><%= link_to "View All Scheduled", root_url %></p><br>
<% end %>

<h4>Active</h4>
<% if @active.blank? %>
  <p>No Active Auctions</p><br>
<% else %>
  <table class="table table-bordered table-striped table-condensed">
    <thead><tr>
      <th>Description</th>    
      <th>URL</th>
      <th>Total Bids</th>
      <th>Price</th>
      <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @active %>
    </tbody>
  </table>
  <p><%= link_to "View All Active", root_url %></p><br>
<% end %>

<h4>Completed</h4>
<% if @completed.blank? %>
  <p>No Completed Auctions</p>
<% else %>
  <table class="table table-bordered table-striped table-condensed">
    <thead><tr>
      <th>Description</th>    
      <th>URL</th>
      <th>Total Bids</th>
      <th>Price</th>
      <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @completed %>
    </tbody>
  </table>
  <p><%= link_to "View All Completed", root_url %></p><br>
<% end %>
<%= link_to 'New Auction', new_auction_path, :class => "btn btn-primary" %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form' %>
<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<div id="auction">
  <h2><%= @auction.description %></h2>
  <div style="float:left" id="nice">
  <p id="auction_summary"><%= render :partial => "summary", :locals => {:auction => @auction} %></p>
  </div>

  <div style="float:right; width:50%">
    <button class="btn btn-danger">Cancel Auction</button>
  </div>
  <div style="clear:both"></div>
  <hr/>

  <h3>Auction History</h3>
  <!-- <div>
    <h4>My Stats</h4>
    <table class="table table-bordered table-striped table-condensed" style="width:70%">
      <thead>
        <th>Bids Placed</th>
        <th>Bids Left</th>
        <th>Exit Now Price</th>
        <th>Last Bid Date</th>
      </thead>
      <tbody>
        <tr>
          <td>50</td>
          <td>40</td>
          <td>$70.25</td>
          <td>Now</td>
        </tr>           
      </tbody>
    </table>
  </div> -->

  <div >
    <h4>Top Bidders</h4>
    <table class="table table-bordered table-striped table-condensed" style="width:70%">
      <thead>
        <th>Bidder</th>
        <th>Total Bids</th>
        <th>Last Bid Time</th>
      </thead>
      <tbody id="most_active_bidders">
        <%= render :partial => "most_active_bidders", :collection => @most_active_bidders %>
      </tbody>
    </table>
  </div>

  <div>
    <h4>Last 5 Bidders</h4>
    <table class="table table-bordered table-striped table-condensed" style="width:70%">
      <thead>
        <th>Bidder</th>
        <th>Total Bids</th>
        <th>Last Bid Time</th>
      </thead>
      <tbody id="last_active_bidders">
        <%= render :partial => "last_active_bidders", :collection => @last_active_bidders %>    
      </tbody>
    </table>
  </div>
  <%= link_to 'Back To Auction List', auctions_path, :class => "btn" %><br><br>
</div>

app/views/auctions/show.js.erb
var topBidders = "<%= escape_javascript(render :partial => 'most_active_bidders', :collection => @most_active_bidders) %>";
var lastBidders = "<%= escape_javascript(render :partial => 'last_active_bidders', :collection => @last_active_bidders) %>";
var auctionSummary = "<%= escape_javascript(render :partial => 'summary', :locals => {:auction => @auction}) %>";

$("#most_active_bidders").html(topBidders);
$("#last_active_bidders").html(lastBidders);
$("#auction_summary").html(auctionSummary);